version: 2.1

orbs:
  codacy: codacy/base@12.1.3
  codacy_plugins_test: codacy/plugins-test@2.0.11

jobs:
  build_docker_and_test:
    docker:
      - image: cimg/python:3.13.5-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Java
          command: |
            sudo apt-get update || true
            sudo apt install -y openjdk-17-jre
            sudo update-java-alternatives --auto
      - run:
          name: Install Python deps
          command: |
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
      - run:
          name: Run doc-generator
          command: |
            curl -sSLf https://virtuslab.github.io/scala-cli-packages/scala-setup.sh | sh
            source ~/.profile
            scala-cli run doc-generator.sc
      - run:
          name: Build and save Docker image
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          root: .
          paths:
            - docker-image.tar

workflows:
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - build_docker_and_test:
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - build_docker_and_test
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
