version: 2.1

orbs:
  codacy: codacy/base@10.8.0
  codacy_plugins_test: codacy/plugins-test@1.1.1

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/sbt:
          name: build_docker_and_test
          cmd: |
            # Install scala-cli
            curl -sSLf https://virtuslab.github.io/scala-cli-packages/scala-setup.sh | sh
            source ~/.profile
            sudo apt-get update # This is failing due to key signature problems
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
            # Run doc-generator
            scala-cli run doc-generator.sc
            # Build and same Docker image
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - build_docker_and_test
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
