apiVersion: v1
kind: Pod
metadata:
  labels:
    run: readonly-container
  name: readonly-container
  namespace: codacy
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
  containers:
  - name: readonly-container
    image: ubuntu@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2
    command: ["/bin/sh", "-c", "sleep infinity"]
    resources:
      requests:
        cpu: 50%
        memory: 100%
      limits:
        cpu: 80%
        memory: 100%
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      runAsUser: 10001
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
  restartPolicy: Never
